compilation:
  cloud_properties:
    name: random
  network: pgbackup
  reuse_compilation_vms: true
  workers: 6
director_uuid: 9bca5701-66c0-43ee-a4d0-64813b4b5ece
jobs:
- instances: 1
  name: pgbackup
  networks:
  - name: pgbackup
    static_ips: null
  persistent_disk: 0
  resource_pool: small_z1
  templates:
  - name: pgbackup
    release: pgbackup
  update:
    canaries: 10
meta:
  environment: postgresbackup-dev
  stemcell:
    name: bosh-warden-boshlite-centos-go_agent
    version: latest
name: postgresbackup-dev
networks:
- name: pgbackup
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []
properties:
  pgbackup:
    host: 127.0.0.1
    name: backups
    password: ""
    port: 5524
    version: "9.4"
releases:
- name: pgbackup
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: pgbackup
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000
